# Generated by Django 4.1 on 2022-08-29 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuisineStyle',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.fooditem')),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='arroz.jpg', null=True, upload_to='')),
                ('dinners', models.IntegerField()),
                ('difficulty', models.IntegerField(choices=[(1, 'Muy fácil'), (2, 'Fácil'), (3, 'Media'), (4, 'Difícil'), (5, 'Muy difícil')])),
                ('fav', models.BooleanField(default=False)),
                ('time', models.IntegerField()),
                ('cuisine_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.cuisinestyle')),
                ('ingredients', models.ManyToManyField(to='recipes.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.quantity'),
        ),
    ]
