# Generated by Django 4.1 on 2022-08-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='fav',
            field=models.BooleanField(default=False),
        ),
    ]
